name: ItemMaker
main: net.battleland.itemmaker.ItemMakerPlugin
version: 0.1

commands:
  createitem:
    usage: /<command> [permission|coins:Int]

permissions:
  createitem.money:
    default: op
  createitem.permission:
    default: false

depend:
  - LuckPerms
  - Essentials
